/** Injection token constants for InversifyJS. */
export const AUTH_SERVICE = "AUTH_SERVICE";
export const GPU_SERVICE = "GPU_SERVICE";
export const GPU_DETECTOR = "GPU_DETECTOR";
export const GPU_ENRICHER = "GPU_ENRICHER";
export const GPU_USAGE_PROBE = "GPU_USAGE_PROBE";
export const SERVICE_MANAGER = "SERVICE_MANAGER";
export const SERVICE_CONTROLLER = "SERVICE_CONTROLLER";
export const SERVICE_CONFIG_CONTROLLER = "SERVICE_CONFIG_CONTROLLER";
export const MANAGED_SERVICES_CONTROLLER = "MANAGED_SERVICES_CONTROLLER";
